# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Jun Yan # Your Name
title: Senior Research Scientist
subtitle: Google

email: junyann [at] google.com
# phone: Your phone number (optional)
# website: Your website (eg. https://google.com)(optional)

# Social links
twitter_username: jun_yannn
github_username: junyann
scholar_username: rhNj2RcAAAAJ
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: jun-yan-731a541ba
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Analytics
analytics_id: UA-152693248-1 

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
# about_content: | # this will include new lines to allow paragraphs

# Publications Section
publications_title: Publications and Preprints #(Use this to override about projects section title)

# Experience Section
experience_title: Research Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: Miscs #(Use this to override about more section title)
# more_content: | # this will include new lines to allow paragraphs
#    I am interested in cyber security.
#    
#    I love cooking.

# Honor Section
# honor_title:

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
